hmcts/adoption-web

Jenkinsfile_CNP, codecept.conf.js, src/test/e2e/actors/base.js, src/test/e2e/config.js, src/test/e2e/pages/LandingPage.js, src/test/e2e/pages/login.page.js, src/test/tests/smoke_test.js
=> E2E for Login and Landing Page

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml
using usePodIdentity: true in charts
=> using usePodIdentity: true in charts

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml
=> Revert "using usePodIdentity: true in charts"

infrastructure/main.tf
=> added s2s secret copy terraform code

src/main/steps/applicant1/applying-with/content.ts, src/main/steps/common/form/fields/radios.njk, src/main/steps/common/template.njk
fixed common template title issue
=> fixed common template title issue

src/main/steps/index.ts, src/main/steps/save-sign-out/get.test.ts, src/main/steps/task-list/content.test.ts, src/main/steps/task-list/content.ts, src/main/steps/task-list/template.njk, src/main/steps/timed-out/get.test.ts, src/main/steps/urls.ts
improved step url logic
this will help us creating urls of `/applicant1/personal-details` format
=> improved step url logic

Jenkinsfile_nightly, codecept.conf.js, src/test/e2e/pages/login.page.js, src/test/e2e/pages/taskList.page.js, src/test/e2e/tests/smoke_test.js, src/test/e2e/tests/taskList_test.js
=> E2E test for Child Eligibility

jest.config.js, src/main/steps/children/childrenSequence.test.ts, src/main/steps/children/childrenSequence.ts, src/main/steps/children/full-name-after-adoption/content.test.ts, src/main/steps/children/full-name-after-adoption/content.ts, src/main/steps/task-list/content.ts, src/main/steps/task-list/template.njk, src/main/steps/task-list/utils.ts, src/main/steps/urls.ts
Added page to capture child's first name and last name after adoption
=> Adop 206 certificate details

src/main/steps/eligibility/lived-uk/content.ts, src/main/steps/eligibility/married/content.ts, src/main/steps/eligibility/under-18/content.ts, src/main/steps/eligibility/under-21/content.ts
Error message corrected as per the UCD prototype in eligibility flow.
=> Error message updated as per UCD prototype.

Jenkinsfile_CNP, package.json, src/test/e2e/pages/login.page.js, src/test/e2e/tests/eligibility_test.js
=> Master Functional Fix

Jenkinsfile_CNP, Jenkinsfile_nightly, bin/run-crossbrowser-tests.sh, package.json, saucelabs.conf.js, src/test/e2e/crossbrowser/supportedBrowsers.js, src/test/e2e/helpers/SauceLabsReportingHelper.js, src/test/e2e/tests/eligibility_test.js, src/test/e2e/tests/taskList_test.js
=> Cross browser config in nightly

src/main/steps/common/components/address-international.test.ts, src/main/steps/common/components/address-international.ts, src/main/steps/common/components/address-manual.test.ts, src/main/steps/common/components/address-manual.ts, src/test/e2e/tests/childDetails_test.js
added common component for international address
=> added common component for international address

Jenkinsfile_CNP, src/test/e2e/config.js
=> Changes in Config file

src/main/app/case/case.ts, src/main/app/case/definition.ts
ADOP 210 ccd mapping
https://tools.hmcts.net/jira/browse/ADOP-210
- [ X] No
=> ADOP 210 ccd mapping

src/main/app/case/case.ts, src/main/app/controller/other-names/OtherNamesGetController.ts, src/main/app/controller/other-names/OtherNamesPostController.test.ts, src/main/app/controller/other-names/OtherNamesPostController.ts, src/main/app/form/Form.ts, src/main/assets/js/index.ts, src/main/assets/js/other-names/submit.ts, src/main/modules/nunjucks/index.ts, src/main/steps/common/components/other-names.ts, src/main/steps/common/form/fields/details.njk
=> Other names error handling

.eslintignore, codecept.conf.js, saucelabs.conf.js
=> Nightly cross browser fix

src/main/steps/children/adoption-agency/content.test.ts, src/main/steps/children/childrenSequence.test.ts, src/main/steps/children/childrenSequence.ts, src/main/steps/children/social-worker/content.test.ts, src/main/steps/children/social-worker/content.ts, src/main/steps/task-list/utils.test.ts, src/main/steps/task-list/utils.ts, src/main/steps/urls.ts, src/test/e2e/pages/childAdoptionAgencyDetails.page.js, src/test/e2e/pages/childDetailsPlacementOrder.page.js, src/test/e2e/pages/otherApplicant.page.js, src/test/e2e/pages/primaryApplicant.page.js, src/test/e2e/tests/childDetails_test.js
ADOP-211 change 
https://tools.hmcts.net/jira/browse/ADOP-211
- [x ] No
=> ADOP-211 change

src/main/steps/sibling/siblingSequence.test.ts, src/main/steps/sibling/siblingSequence.ts
fixed sonar issue in siblingSequence file
=> fixed sonar issue

codecept.conf.js, saucelabs.conf.js, src/test/e2e/pages/LandingPage.js, src/test/e2e/pages/childDetailsPlacementOrder.page.js, src/test/e2e/pages/primaryApplicant.page.js, src/test/e2e/pages/primaryApplicantPersonalDetails.page.js, src/test/e2e/pages/reviewPayAndSubmit.page.js, src/test/e2e/pages/taskList.page.js, src/test/e2e/tests/applicantDetails_test.js, src/test/e2e/tests/childDetails_test.js, src/test/e2e/tests/eligibility_test.js, src/test/e2e/tests/otherApplicantDetails_test.js, src/test/e2e/tests/primaryApplicantDetails_test.js, src/test/e2e/tests/submitAdoptionApplication_test.js, src/test/e2e/tests/taskList_test.js
=> E2E for Review and Pay

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, src/main/app/case/case.ts, src/main/app/case/definition.ts, src/main/modules/properties-volume/index.ts, src/main/steps/review-pay-submit/equality/PcqParameters.ts, src/main/steps/review-pay-submit/equality/content.ts, src/main/steps/review-pay-submit/equality/createToken.test.ts, src/main/steps/review-pay-submit/equality/createToken.ts, src/main/steps/review-pay-submit/equality/get.test.ts, src/main/steps/review-pay-submit/equality/get.ts, src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts, src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts, src/main/steps/task-list/content.ts, src/main/steps/urls.ts
PCQ changes
https://tools.hmcts.net/jira/browse/ADOP-25
- [ x] No
=> PCQ change

Jenkinsfile_CNP, src/main/assets/js/cookie.ts
=> whitlelisted oauth cookie

charts/adoption-web/Chart.yaml, charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, src/main/modules/properties-volume/index.ts
=> Adop app insights

src/main/steps/sibling/siblingSequence.test.ts, src/main/steps/sibling/siblingSequence.ts
fixed bug related to empty sibling name
https://tools.hmcts.net/jira/browse/ADOP-609
=> fixed bug related to empty sibling name

src/main/steps/accessibility-statement/content.ts, src/main/steps/accessibility-statement/get.test.ts, src/main/steps/accessibility-statement/get.ts, src/main/steps/accessibility-statement/template.njk, src/main/steps/cookies/content.ts, src/main/steps/cookies/get.test.ts, src/main/steps/cookies/get.ts, src/main/steps/cookies/template.njk, src/main/steps/privacy-policy/content.ts, src/main/steps/privacy-policy/get.test.ts, src/main/steps/privacy-policy/get.ts, src/main/steps/privacy-policy/template.njk, src/main/steps/terms-and-conditions/content.ts, src/main/steps/terms-and-conditions/get.test.ts, src/main/steps/terms-and-conditions/get.ts, src/main/steps/terms-and-conditions/template.njk
Code introduced to have footer links.
=> Footer links and their respective pages added.

src/main/modules/csrf/index.ts
ignored dynatrace monitor endpoint from csurf
https://tools.hmcts.net/jira/browse/ADOP-669
=> ignored dynatrace monitor endpoint from csurf

charts/adoption-web/values.preview.template.yaml, config/default.yaml
=> pcq attribute update

charts/adoption-web/values.preview.template.yaml, src/main/steps/review-pay-submit/equality/get.ts
=> updated pcq logs

yarn.lock
updated json-schema version to 0.4.0
https://tools.hmcts.net/jira/browse/ADOP-666
=> json-schema vulnerability fix

Jenkinsfile_nightly
Fortify scan for frontend enabled.
=> Fortify scan hook added in the nightly.

Jenkinsfile_CNP
stop ithc perftest branch sync
=> stop ithc perftest branch sync

src/main/steps/review-pay-submit/equality/get.ts
added pcq log statements.
- [ x] No
=> PCQ logging

src/test/a11y/a11y.ts
=> changed pa11y output location

src/main/steps/privacy-policy/template.njk
Fixed accessibility issue which was breaking build.
=> Fixed accessibility issue on privacy policy page.

src/main/steps/task-list/utils.ts
fixed sonar error in  task-list-utils statementOfTruthAndPaymentStatus method
=> fixed sonar error

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, src/test/pact/ccd-data-store-api.test.ts
Removed cpu and memory params from values.yaml
=> removed cpu and memory params from values.yaml

charts/adoption-web/values.preview.template.yaml, src/main/modules/session/index.test.ts, src/main/modules/session/index.ts, src/main/server.ts
added secure flag to session cookie to fix ithc security finding
=> added secure flag to session cookie

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/adoption-web/Chart.yaml, charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/default.yaml, config/development.yaml, src/main/app/auth/service/get-service-auth-token.integration.test.ts, src/main/app/auth/user/oidc.integration.test.ts, src/main/app/fee/fee-lookup-api.integration.test.ts, src/main/modules/properties-volume/index.ts, src/test/config.ts, src/test/smoke/smoke.ts
remove internal url references
using endpoints from keyvault for local development 
=> remove internal url references

charts/adoption-web/Chart.yaml, charts/adoption-web/values.aat.template.yaml
increased pod size for aat staging
=> increased pod size for aat staging

src/main/modules/properties-volume/index.ts
made setLocalEndpoints private
=> made setLocalEndpoints private

src/main/server.ts
added fix for zap security issue related to options and trace methods
disabled x-powered-by requests
https://tools.hmcts.net/jira/browse/ADOP-850
=> added fix for zap security issue related to options and trace methods

src/main/server.ts
added fix for zap 40025 issue
https://tools.hmcts.net/jira/browse/ADOP-850
=> added fix for zap 40025 issue

src/main/steps/children/placement-order-check-your-answers/content.test.ts, src/main/steps/children/placement-order-check-your-answers/content.ts, src/main/steps/children/placement-order-summary/content.test.ts, src/main/steps/children/placement-order-summary/placement-order-summary.test.ts, src/main/steps/children/placement-order-summary/placement-order-summary.ts, src/main/steps/review-pay-submit/check-your-answers/utils.test.ts, src/main/steps/review-pay-submit/check-your-answers/utils.ts, src/main/steps/sibling/placement-order-check-your-answers/content.test.ts, src/main/steps/sibling/placement-order-check-your-answers/content.ts, src/main/steps/sibling/summary/placement-order-summary.test.ts, src/main/steps/sibling/summary/placement-order-summary.ts
fixed a11y issue on child PO change / remove link
fixed a11y issue on sibling PO change / remove link
https://tools.hmcts.net/jira/browse/ADOP-691
=> Adop 691 a11y bugfix

audit.json
=> zap issue fix

src/test/pact/ccd-data-store-api.test.ts, src/test/pact/dm-store.test.ts, src/test/pact/fees-register-api.test.ts, src/test/pact/idam-api.test.ts, src/test/pact/payment-api.test.ts, src/test/pact/rpe-service-auth-provider.test.ts
=> modified providers

src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts, src/main/steps/review-pay-submit/payment/payment-callback/get.ts
redirect to statement-of-truth after cancel payment
https://tools.hmcts.net/jira/browse/ADOP-697
=> ADOP-697 cancel payment redirect

bin/remove-stuck-pr.sh, jest.pact.config.js, src/test/pact/ccd-data-store-api.test.ts
fix pact test issue related to jest 28.x
=> fix pact test issue related to jest 28.x

infrastructure/main.tf
upgrading to redis_version 6 in terraform
=> upgrading to redis_version 6 in terraform

Jenkinsfile_nightly
Stopping fortify scan until we have false positive issue ignored.
=> Stopping fortify until false positive issue is fixed.

src/main/steps/children/find-family-court/FindFamilyCourtPostController.test.ts, src/main/steps/children/find-family-court/FindFamilyCourtPostController.ts
=> Bugfix family court name

src/test/e2e/crossbrowser/supportedBrowsers.js
=> Update Browser version

src/main/assets/js/cookie.ts
=> Cookies fix.

src/main/app/case/CaseApi.integration.test.ts, src/main/app/case/CaseApi.ts, src/test/steps/common.ts
https://tools.hmcts.net/jira/browse/ADOP-910
=> Elastic search API implementation to fetch the case from data store.

src/test/e2e/pages/dateChildMovedinDetails.page.js
=> ADOP-1031 Test changes

src/main/steps/application/privacy-policy/content.test.ts, src/main/steps/application/privacy-policy/content.ts, src/main/steps/application/privacy-policy/template.njk, src/main/steps/application/terms-and-conditions/content.test.ts, src/main/steps/application/terms-and-conditions/content.ts, src/main/steps/application/terms-and-conditions/template.njk, src/main/steps/common/common.content.ts, src/main/steps/common/cookie-banner.njk, src/main/steps/common/page.njk, src/main/steps/la-portal/laPortalSequence.test.ts, src/main/steps/la-portal/laPortalSequence.ts, src/main/steps/urls.ts
https://tools.hmcts.net/jira/browse/ADOP-1016
=> Footer links with la-portal context path when used from LA portal.

Jenkinsfile_nightly, src/main/steps/applicant1/date-child-moved-in/content.test.ts, src/main/steps/applicant1/date-child-moved-in/content.ts
Updated error message for Child Move in date
https://tools.hmcts.net/jira/browse/FPET-38
- [ x] No
=> FPET-38 Updated error message for Child Move in date

Jenkinsfile_nightly, saucelabs.conf.js
To remove the cross browser array
https://tools.hmcts.net/jira/browse/FPET-49
=> removed cross browser array

src/main/steps/common/page.njk
=> Feedback link for la-portal

src/main/steps/children/applicant-social-worker/content.test.ts, src/main/steps/children/applicant-social-worker/content.ts, src/main/steps/children/social-worker/content.test.ts, src/main/steps/children/social-worker/content.ts
CUI - Adoption agency and social worker - Modify hint message on Child's social worker details page & Your social worker details
[### JIRA link](https://tools.hmcts.net/jira/browse/ADOP-1094)
=> ADOP - 1094 - Update Adoption Agency Social Worker Email Hint

charts/adoption-web/Chart.yaml, charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, src/main/app/auth/user/oidc.integration.test.ts, src/main/app/auth/user/oidc.ts, src/main/app/case/CaseApi.integration.test.ts, src/main/app/controller/AppRequest.ts, src/main/app/court/court-venues-api.integration.test.ts, src/main/app/document/DocumentManagementClient.integration.test.ts, src/main/app/document/DocumentManagementClient.ts, src/main/app/document/DocumentManagementController.ts, src/main/modules/oidc/index.ts, src/main/modules/properties-volume/index.ts, src/test/steps/IdamUserManager.ts, src/test/steps/common.ts
=> resolved conflict

charts/adoption-web/Chart.yaml
=> Upgraded nodeJs in  chart 

src/main/steps/common/form/contactForHelp.njk
LA Portal - Contact us for help
[### JIRA link](https://tools.hmcts.net/jira/browse/ADOP-1082)
Does this PR introduce a breaking change? (check one with "x")
Yes
[X]No
=> Add contact us section la portal

charts/adoption-web/values.yaml, config/custom-environment-variables.yaml, config/default.yaml
=> dynamic ref api url based on env

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/custom-environment-variables.yaml, config/default.yaml
=> LOCATION_API_URL update

charts/adoption-web/values.preview.template.yaml
=> preview issue

src/main/steps/application/task-list/content.test.ts, src/main/steps/application/task-list/content.ts
=> task-list changes

config/default.yaml, package.json
=> Local config changes for tls

charts/adoption-web/values.preview.template.yaml, codecept.conf.js, config/default.yaml, draft-store.yml, saucelabs.conf.js, src/main/app/case/definition.ts, src/main/app/controller/PostController.test.ts, src/main/app/controller/PostController.ts, src/main/app/form/validation.test.ts, src/main/app/form/validation.ts, src/main/modules/kba/index.ts, src/main/steps/application/task-list/utils.ts, src/main/steps/la-portal/check-your-answers/content.ts, src/main/steps/la-portal/laPortalSequence.test.ts, src/main/steps/la-portal/laPortalSequence.ts, src/main/steps/la-portal/statement-of-truth/content.test.ts, src/main/steps/la-portal/statement-of-truth/content.ts, src/main/steps/la-portal/statement-of-truth/form.njk, src/main/steps/la-portal/statement-of-truth/template.njk, src/main/steps/la-portal/task-list/utils.test.ts, src/main/steps/la-portal/task-list/utils.ts, src/main/steps/urls.ts, src/test/e2e/pages/laCheckYourAnswers.page.js, src/test/e2e/pages/reviewPayAndSubmit.page.js, src/test/e2e/pages/taskList.page.js, src/test/e2e/pages/uploadDocumentsDetails.page.js, src/test/e2e/tests/saveAsDraft_test.js, src/test/e2e/tests/submitAdoptionApplication_test.js
=> Adop 1086 & 1130

config/default.yaml, src/main/modules/draft-store/index.ts
=> Logger update

src/main/steps/la-portal/confirmation/template.njk, src/main/steps/la-portal/task-list/template.njk, src/test/a11y/a11y.ts
=> Enabled Pally tests for LA_PORTAL

.eslintrc.js, src/main/steps/sibling/placement-order-check-your-answers/content.test.ts, src/main/steps/sibling/placement-order-check-your-answers/content.ts, src/main/steps/sibling/remove-placement-order/content.test.ts, src/main/steps/sibling/remove-placement-order/content.ts
=> Fpet 135 : Google Analytics Fixes

charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/default.yaml, src/main/app/case/CaseApi.integration.test.ts, src/main/app/case/CaseApi.ts, src/main/modules/draft-store/draft-store-service.ts, src/main/modules/state-redirect/index.ts
=> Es disable

charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/default.yaml, src/main/app/case/CaseApi.integration.test.ts, src/main/app/case/CaseApi.ts, src/main/modules/draft-store/draft-store-service.ts, src/main/modules/state-redirect/index.ts
* fixes
* es disabled
* added time in days
=> Es disable (#783)

src/main/app/document/DocumentManagementController.test.ts, src/main/app/document/DocumentManagementController.ts, src/main/modules/draft-store/draft-store-service.ts, src/test/unit/utils/mockRequest.ts
Redis upload document issue resolve
=> ADOP-REDIS-ISUE: Redis document upload issue fix

src/main/app/case/CaseApi.integration.test.ts, src/main/app/case/CaseApi.ts
Enable elastic search. Existing changes revert
=> Elastic search enable

Jenkinsfile_CNP, src/test/pact/ccd-data-store-api.test.ts, src/test/pact/rpe-service-auth-provider.test.ts
=> Enable PACT Tests

charts/adoption-web/values.preview.template.yaml, src/main/app/case/case.ts, src/main/app/case/definition.ts, src/main/app/controller/PostController.ts
=> ADOP-1415-LAPortal-Docmosis

charts/adoption-web/values.preview.template.yaml, src/main/app/payment/PaymentModel.ts, src/main/steps/review-pay-submit/payment/pay-your-fee/get.ts, src/main/steps/review-pay-submit/payment/payment-callback/get.ts
=> ADOP-348 payment tab changes

src/main/steps/la-portal/check-your-answers/utils.ts
=> Upload Document name issue fix

src/main/app/court/court-venues-api.ts
=> Removing additional call to ref-data-api

src/main/app/case/definition.ts
=> fix: Demo-Environment-Fix

src/main/steps/applicant1/applicant1Sequence.ts, src/main/steps/application/task-list/utils.ts, src/main/steps/sibling/placement-order/get.ts, src/main/steps/sibling/relation/SiblingGetController.ts, src/main/steps/sibling/relation/SiblingPostController.ts
Fix sonar issues in adoption-web
https://tools.hmcts.net/jira/browse/ADOP-1206
=> Fix sonar issues in adoption-web

src/test/pact/ccd-data-store-api.test.ts
=> Adop 1679 enabling pact

src/test/e2e/fixtures/caseData/applicantOrYourSocialWorkerDetails.js, src/test/e2e/fixtures/caseData/childAdoptionAgencyDetails.js, src/test/e2e/fixtures/caseData/childBasicDetails.js, src/test/e2e/fixtures/caseData/childSocialWorkerDetails.js, src/test/e2e/pages/childAdoptionAgencyDetails.page.js, src/test/e2e/pages/childsDetails.page.js, src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js, src/test/e2e/pages/dateChildMovedinDetails.page.js, src/test/e2e/pages/otherApplicant.page.js, src/test/e2e/pages/otherApplicantPersonalDetails.page.js, src/test/e2e/pages/primaryApplicantPersonalDetails.page.js, src/test/e2e/tests/e2enegative_test.js
=> CUI Negative test case

src/main/steps/children/find-family-court/util.ts
- [ * ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/FPET-228
- [ * ] No
=> enabling trigger word search for courts

config/test.yaml, src/main/app/auth/user/oidc.integration.test.ts
- [x ] commit messages are meaningful and follow good commit message guidelines
Fixed FPET-259 Moved the test data to test.yml
https://tools.hmcts.net/jira/browse/FPET-259
- [X ] No
=> Fixed FPET-259 Moved the test data to test.yml

src/main/steps/la-portal/check-your-answers/utils.ts
=> Fixed Document Upload Issue

src/main/steps/common/components/nationality.test.ts, src/main/steps/common/components/nationality.ts
=> ADOP-1876-Defect-LabelNationality

charts/adoption-web/values.preview.template.yaml, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/FPET-315
=> Fix nightly build failures for Adoption-web 

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/FPET-359
=> Vulnerability fix for cookiejar : CVE-2022-25901

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-361
=> updated email address for liverpool court

src/main/steps/la-portal/task-list/utils.ts
=> ADOP-2176-RegressionDefect

src/main/steps/application/task-list/content.test.ts, src/main/steps/application/task-list/content.ts, src/main/steps/review-pay-submit/check-your-answers/content.test.ts, src/main/steps/review-pay-submit/check-your-answers/content.ts, src/test/e2e/fixtures/caseData/checkYourAnswersPageKeysDetails.js
https://tools.hmcts.net/jira/browse/ADOP-2178
=> ADOP-2178: Task list and review answer content changes

src/main/steps/application/submitted/content.test.ts, src/main/steps/application/submitted/content.ts, src/main/steps/application/submitted/template.njk
https://tools.hmcts.net/jira/browse/ADOP-2179
=> ADOP 2179: Application submitted/confirmation page content changes

src/main/steps/common/common.content.ts, src/main/steps/common/page.njk, src/main/steps/la-portal/task-list/content.test.ts, src/main/steps/la-portal/task-list/content.ts, src/test/e2e/pages/LandingPage.js, src/test/e2e/pages/taskList.page.js
=> ADOP-2157-LA-URChanges

src/main/steps/application/task-list/content.test.ts, src/main/steps/application/task-list/content.ts, src/main/steps/application/task-list/template.njk
=> ADOP-2052-Accessibility Testing - Non-Descriptive Links

src/main/steps/review-pay-submit/pay-and-submit/content.test.ts, src/main/steps/review-pay-submit/pay-and-submit/content.ts, src/main/steps/review-pay-submit/pay-and-submit/template.njk, src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts, src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts, src/main/steps/urls.ts, src/test/e2e/pages/reviewPayAndSubmit.page.js, src/test/e2e/tests/e2enegative_test.js, src/test/e2e/tests/saveAsDraft_test.js, src/test/e2e/tests/submitAdoptionApplication_test.js
=> ADOP-2169: CUI - Pay and submit page - Part 1

charts/adoption-web/Chart.yaml, src/main/app/controller/AppRequest.ts, src/main/steps/eligibility/eligibilitySequence.test.ts, src/main/steps/eligibility/eligibilitySequence.ts, src/main/steps/eligibility/multiple-children-desc/content.test.ts, src/main/steps/eligibility/multiple-children-desc/content.ts, src/main/steps/eligibility/multiple-children-desc/post.ts, src/main/steps/eligibility/multiple-children-desc/template.njk, src/main/steps/eligibility/multiple-children/content.test.ts, src/main/steps/eligibility/multiple-children/content.ts, src/main/steps/eligibility/multiple-children/post.ts, src/main/steps/eligibility/start/template.njk, src/main/steps/index.test.ts, src/main/steps/urls.ts, src/test/e2e/pages/login.page.js
https://tools.hmcts.net/jira/browse/ADOP-2175 
=> ADOP-2175 multiple children changes

src/main/app/case/CaseApi.integration.test.ts, src/main/app/case/CaseApi.ts, src/main/app/controller/PostController.ts, src/main/modules/oidc/index.ts, src/main/steps/application/home/get.ts
=> ADOP-2186-Case reference generation logic to move from IDAM login page to 'Apply with' page submission.

src/main/steps/eligibility/EligibilityPostController.ts
=> ADOP-2196-Multiple Children - Eligibility screen redirection logic

src/main/app/document/DocumentManagementClient.integration.test.ts, src/main/app/document/DocumentManagementClient.ts, src/main/assets/js/upload-manager/index.ts, src/main/steps/la-portal/upload-your-documents/content.test.ts, src/main/steps/la-portal/upload-your-documents/content.ts
=> ADOP-2096-Increased file size to 50 MB

src/main/steps/applicant1/other-names/content.test.ts, src/main/steps/applicant1/other-names/content.ts, src/main/steps/applicant2/other-names/content.test.ts, src/main/steps/applicant2/other-names/content.ts, src/main/steps/birth-father/nationality/content.test.ts, src/main/steps/birth-father/nationality/content.ts, src/main/steps/birth-mother/nationality/content.test.ts, src/main/steps/birth-mother/nationality/content.ts, src/main/steps/children/nationality/content.test.ts, src/main/steps/children/nationality/content.ts, src/main/steps/common/components/nationality.ts, src/main/steps/common/components/other-names.ts, src/main/steps/review-pay-submit/check-your-answers/content.test.ts, src/main/steps/review-pay-submit/check-your-answers/content.ts
=> ADOP-15: Welsh translation fixes

charts/adoption-web/Chart.yaml
=> update chart version

charts/adoption-web/Chart.yaml
=> updated node version in helm chart to fix helm issues

Jenkinsfile_CNP, src/test/e2e/config.js
https://tools.hmcts.net/jira/browse/FPET-419
=> Updating the service url to platform.hmcts.net from .internal

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, src/main/steps/eligibility/married/content.test.ts, src/main/steps/eligibility/married/content.ts
=> Updated the text content on eligibility screen

Jenkinsfile_CNP, src/test/e2e/config.js
=> FPET-492 master build

src/test/e2e/pages/LandingPage.js, src/test/e2e/pages/login.page.js, src/test/e2e/tests/eligibility_test.js, src/test/e2e/tests/smoke_test.js, src/test/e2e/tests/submitAdoptionApplication_test.js
=> 473 testfailure

Jenkinsfile_CNP, src/test/e2e/config.js
=> FPET-473 Staging URL fix

src/main/app/controller/PostController.test.ts, src/main/steps/review-pay-submit/check-your-answers/CheckYouAnswersPostController.test.ts
=> Feature fpet 529 junit

charts/adoption-web/values.preview.template.yaml, src/main/modules/kba/index.ts
=> enble fortify in PR

src/main/modules/kba/index.ts, src/main/steps/children/full-name/content.ts
=> INC5516362 fix

package.json, yarn.lock
=> Nightly Cross Browser Fix 

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
=> SNI-4308-whitelisted another LA email

charts/adoption-web/values.preview.template.yaml, package.json, src/main/app/address/ManualAddressPostControllerBase.test.ts, src/main/app/address/SelectAddressPostControllerBase.test.ts, src/main/app/case/case.ts, src/main/app/controller/PostController.test.ts, src/main/app/controller/PostController.ts, src/main/app/controller/other-names/OtherNamesPostController.test.ts, src/main/app/nationality/NationalityPostController.test.ts, src/main/steps/applicant2/same-address/SameAddressPostController.test.ts, src/main/steps/children/find-family-court/FindFamilyCourtPostController.test.ts, src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.test.ts, src/main/steps/children/placement-order/PlacementOrderPostController.test.ts, src/main/steps/review-pay-submit/check-your-answers/CheckYouAnswersPostController.test.ts, src/main/steps/review-pay-submit/check-your-answers/CheckYouAnswersPostController.ts, src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts, src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts, src/main/steps/sibling/placement-order/post.test.ts, src/main/steps/sibling/relation/SiblingPostController.test.ts, src/main/steps/sibling/remove-placement-order/SiblingRemovePlacementOrderPostController.test.ts, yarn.lock
Fixing the scenario where payment was not being asked if user comes to SOYT Page just before the 12AM mark and then clicks the button after 12AM in that case payment was not taken. Ideally it should have asked for payment.
=> Multi Child Payment issue on SOT

src/main/steps/common/form/form.njk
=> FPET-619 added autocomplete feature

charts/adoption-web/Chart.yaml, charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/default.yaml
=> FPET-687- added email domains for LA email address

src/main/app/case/answers/formatDate.ts, src/main/modules/kba/index.ts
=> FPET-592- LA portal Date format update on start page

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
=> FPET-687-added LA email to exception list

audit.json
=> FPET-698- fixed security scan issue

src/test/e2e/fixtures/caseData/checkYourAnswersPageKeysDetails.js, src/test/e2e/pages/checkYourAnswers.page.js, src/test/e2e/pages/otherApplicant.page.js, src/test/e2e/pages/primaryApplicant.page.js
=> FPET-628 - Update Functional test

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
=> FPET-712-added LA email domain to allowed list

src/main/steps/birth-father/alive/content.test.ts, src/main/steps/birth-father/alive/content.ts, src/main/steps/review-pay-submit/check-your-answers/content.ts, src/main/steps/review-pay-submit/check-your-answers/utils.ts
=> FPET-710-updated welsh text

Jenkinsfile_CNP
=> sync demo, ithc and perftest with master

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-745
=> FPET-745-added LA email to allowed domain list

charts/adoption-web/Chart.yaml, charts/adoption-web/values.preview.template.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-749
=> FPET-749-added LA email domain to allowed list

src/main/steps/children/find-family-court/util.ts
Adoption Tranche 3 Court email address Release 
https://tools.hmcts.net/jira/browse/FPET-719
=> FPET-719-Adoption Tranche 3 Court email address Release

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-764
=> FPET-764-added LA email domain to allowed list

charts/adoption-web/values.preview.template.yaml, src/main/steps/application/accessibility-statement/content.test.ts, src/main/steps/application/accessibility-statement/content.ts, src/main/steps/application/accessibility-statement/template.njk
Adoption- Update accessibility statement based on Accessibility testing sign off -  Must have for public beta release
https://tools.hmcts.net/jira/browse/FPET-572
=> FPET-572-accessibility page changes

src/main/steps/application/task-list/utils.test.ts, src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
=> Sonar fixes prod

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-764
=> FPET-764-corrected LA domain from allowed list

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-775
=> FPET-775-added LA email domain to allowed list

.github/renovate.json, charts/adoption-web/values.preview.template.yaml
=> Suppressed the renovate automaerge

charts/adoption-web/values.preview.template.yaml, src/main/app/case/CaseApi.ts, src/main/app/case/NewCaseRedirectController.test.ts, src/main/app/case/NewCaseRedirectController.ts, src/main/app/controller/AppRequest.ts, src/main/app/controller/PostController.test.ts, src/main/app/controller/PostController.ts, src/main/modules/oidc/index.ts, src/main/steps/application/home/get.test.ts, src/main/steps/application/home/get.ts, src/main/steps/eligibility/EligibilityPostController.test.ts, src/main/steps/eligibility/EligibilityPostController.ts
Reduces the number of searchCases api calls being made on the applying-with page.
https://tools.hmcts.net/jira/browse/FPET-777
=> FPET-777: Fix applying-with performance issues

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
Adds LA email domain to allowed list
https://tools.hmcts.net/jira/browse/FPET-779
=> FPET-779: Add LA email domain to allowed list

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/FPET-810
=> FPET-810-added LA email domain to allowed list

broker-compose.yaml
Fix broken nightly pipeline
https://tools.hmcts.net/jira/browse/ADOP-2351
=> Fix fortify

src/main/steps/application/privacy-policy/content.test.ts, src/main/steps/application/privacy-policy/content.ts
Content Update
https://tools.hmcts.net/jira/browse/ADOP-2365
- [ x] No
=> ADOP_2365_Content_Update

src/main/steps/eligibility/start/content.test.ts, src/main/steps/eligibility/start/content.ts
temporary change to test ithc pipeline
https://tools.hmcts.net/jira/browse/ADOP-2323
=> [ADOP-2323] temporary change to test ithc pipeline

.gitignore, Jenkinsfile_nightly, package.json, playwright-e2e/settings/urls.ts, playwright-e2e/smoke.spec.ts, playwright.config.ts, test-results/result.xml, yarn.lock
Setup playwright framework for adoption-web
https://tools.hmcts.net/jira/browse/ADOP-2403
=> ADOP-2403 Setup playwright framework for adoption-web

charts/adoption-web/values.preview.template.yaml
Housekeeping to point preview back to AAT build
=> ADOP-2376-restore-preview-aat

src/test/api/fee-register.api.test.ts, src/test/e2e/pages/reviewPayAndSubmit.page.js, src/test/pact/fees-register-api.test.ts, src/test/pact/payment-api.test.ts
Adoption fee increased from £183 to £201 effective 1st May 2024. This PR updates hard-coded test values to reflect this change.
https://tools.hmcts.net/jira/browse/ADOP-2429
=> [ADOP-2429] Updating tests to reflect fee increase

src/test/api/fee-register.api.test.ts, src/test/e2e/pages/reviewPayAndSubmit.page.js, src/test/pact/fees-register-api.test.ts, src/test/pact/payment-api.test.ts
Updating versions of fees (this was missed in https://github.com/hmcts/adoption-web/pull/1529)
https://tools.hmcts.net/jira/browse/ADOP-2429
=> ADOP-2429 Update tests to reflect new fee/version

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
Adding new social worker domain.
https://tools.hmcts.net/jira/browse/ADOP-2457
=> [ADOP-2457] Added social worker domain

playwright-e2e/pages/base-page.ts, playwright-e2e/pages/eligibility-pages.ts, playwright-e2e/tests/eligibility-one-child.spec.ts
aims to create Playwright tests to verify error messaging across eligibility questions. The goal is to ensure consistent and accurate error handling throughout eligibility questions (before log in).
https://tools.hmcts.net/jira/browse/ADOP-2459
=> ADOP-2459: Eligibility error checking

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
Added a new social worker domain
https://tools.hmcts.net/jira/browse/ADOP-2462
=> [ADOP-2462] added new social worker domain

charts/adoption-web/Chart.yaml, charts/adoption-web/values.yaml, config/default.yaml
Add new social worker domain
https://tools.hmcts.net/jira/browse/ADOP-2471
=> [ADOP-2471] adding new social worker domain

src/main/steps/application/accessibility-statement/content.test.ts, src/main/steps/application/accessibility-statement/content.ts, src/main/steps/application/accessibility-statement/template.njk, src/main/steps/application/contact-us/content.test.ts, src/main/steps/application/contact-us/content.ts, src/main/steps/application/contact-us/template.njk, src/main/steps/common/common.content.ts, src/main/steps/common/form/contactForHelp.njk
Update Contact us with court finder link.
https://tools.hmcts.net/jira/browse/ADOP-2301
- [x ] No
=> Adop 2301 update contact

Jenkinsfile_CNP, Jenkinsfile_nightly, playwright-e2e/helpers/idamTestApiHelpers.ts, playwright-e2e/hooks/createDeleteUser.hook.ts
fixes failing playwright test by adding secrets to azure key vault
- [ x] No
=> ADOP: Add secret idam access token

playwright-e2e/pages/app.page.ts, playwright-e2e/pages/applicantsDetails.page.ts, playwright-e2e/pages/childDetails.page.ts, playwright-e2e/pages/dateChildMoved.page.ts, playwright-e2e/pages/numberOfApplicants.page.ts, playwright-e2e/pages/reviewSubmit.page.ts, playwright-e2e/pages/taskList.page.ts, playwright-e2e/tests/smoke.spec.ts, playwright-e2e/tests/submit-application-journey.spec.ts
Enhance the current Playwright smoke test, which only checks for a page title. Expand the test to include verification of key elements and basic functionalities to improve deployment validation.
Requirements:
1. Retain Title Check: Ensure the current title check remains.
2. Complete basic functionality test 
Objective:
Improve test coverage to catch issues early and ensure basic functionality post-deployment.
[### JIRA link](https://tools.hmcts.net/jira/browse/ADOP-2505)
- [ x] No
=> ADOP-2505: Improve playwright smoke test

package.json, yarn.lock
=> vulnerability fix

src/main/steps/common/cookie-banner.njk
Add Dynatrace RUM script to cookie banner.
https://tools.hmcts.net/jira/browse/ADOP-2514
=> [ADOP-2514] Add Dynatrace RUM for production

audit.json
Suppress zapscan to fix nightly pipelines.
TBC
=> Suppress zapscan

src/main/steps/common/cookie-banner.njk
fix tag
[ADOP-2514](https://tools.hmcts.net/jira/browse/ADOP-2514)
=> Fix cookie banner script - `prod` not `production`

package.json, yarn.lock
Update nanoid to >=3.3.8 (vulnerability fix)
N/A
=> Update nanoid to >=3.3.8 (vulnerability fix)

src/main/steps/review-pay-submit/pay-and-submit/content.test.ts, src/main/steps/review-pay-submit/pay-and-submit/content.ts, src/main/steps/review-pay-submit/pay-and-submit/template.njk
Improve wording so Citizens expect Adoption application-submitted page and confirmation email
https://tools.hmcts.net/jira/browse/ADOP-2559
=> ADOP-2559 Improve wording so Citizens expect Adoption application-submitted page and confirmation email

playwright-e2e/page-objects/citizen/payments/citSubmittedPage.page.ts, playwright-e2e/tests/full_journey/e2e-citizen-la-journey-tests.spec.ts
=> ADOP-2618 - e2e test coverage fixes

package.json, yarn.lock
update axe-core and playwright to be able to use new features.
=> Update playwright to 1.50

package.json, playwright.config.ts
=> removed samsung emulations

package.json, yarn.lock
=> bump axios

package.json
=> ADOP-2647 Master pipeline smoke test fix SCOUTING

Jenkinsfile_CNP
=> archive reports folder after smoke test

Jenkinsfile_CNP
=> Edit archive

Jenkinsfile_CNP, playwright-e2e/tests/smoke.spec.ts, playwright-e2e/utils/toggles.ts
=> ADOP-2647 - env variable type changes

src/test/api/fee-register.api.test.ts, src/test/pact/fees-register-api.test.ts, src/test/pact/payment-api.test.ts
Fee version was previously 3 but seems to have jumped to 5 rather than 4 as expected.
https://tools.hmcts.net/jira/browse/ADOP-2621
=> [ADOP-2641] update fee version to 5

Jenkinsfile_CNP
=> ADOP-2648 fix

Jenkinsfile_CNP
=> ADOP-2648: master fix

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/variables.tf
Upgrade perftest to Standard SKU (temporarily so we can upgrade to premium)
https://tools.hmcts.net/jira/browse/ADOP-2323
=> Upgrade perftest to Standard SKU

infrastructure/variables.tf
=> Update max snapshot count to 1

infrastructure/perftest.tfvars
Upgrade redis cache for perftest to premium sku
https://tools.hmcts.net/jira/browse/ADOP-2323
=> Upgrade redis cache for perftest to premium sku

infrastructure/perftest.tfvars
Downgrade perftest redis cache to Basic SKU
https://tools.hmcts.net/jira/browse/ADOP-2323
=> Downgrade perftest redis cache to Basic SKU

infrastructure/perftest.tfvars
=> ADOP-2323: Upgrade redis cache to premium tier

package.json, yarn.lock
=> upgraded axios dependency to 1.12.0
